---
- name: Pull docker image of Calculator
  hosts: all
  tasks: 
  
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/dhruvkharkwal/spe_miniproject
      
    - name: running container
      shell: docker run -it -d dhruvkharkwal/spe_miniproject
 
